version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["deps","github-actions"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["deps","python"]
    open-pull-requests-limit: 10
