from __future__ import annotations

from collections.abc import Mapping
from typing import Any

_SEVERITIES = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]


def _get_counts(summary: Mapping[str, Any]) -> dict[str, int]:
    counts: dict[str, int] = {}
    by = summary.get("by_severity", {}) or {}
    if isinstance(by, Mapping):
        for sev in _SEVERITIES:
            # Acepta claves en minúsculas o MAYÚSCULAS
            counts[sev] = int(by.get(sev, by.get(sev.lower(), 0)) or 0)
    return counts


def to_markdown(summary: Mapping[str, Any]) -> str:
    counts = _get_counts(summary)
    total = int(summary.get("total", 0) or 0)
    worst = str(summary.get("worst", "INFO") or "INFO").upper()
    risk = str(summary.get("risk", "green") or "green").lower()

    risk_emoji = {"red": "🔴", "yellow": "🟡", "green": "🟢"}.get(risk, "🟢")
    lines = []
    lines.append(f"# Diff Risk Dashboard {risk_emoji} — Worst: **{worst}**")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|---|---:|")
    for sev in _SEVERITIES:
        lines.append(f"| {sev} | {counts.get(sev, 0)} |")
    lines.append(f"| **TOTAL** | **{total}** |")
    lines.append("")
    lines.append("> Generated by diff-risk-dashboard CLI")
    return "\n".join(lines)
