from __future__ import annotations

_SEVERITIES = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]


def to_markdown(summary: dict) -> str:
    counts = {s: int(summary.get("by_severity", {}).get(s, 0)) for s in _SEVERITIES}
    total = int(summary.get("total", sum(counts.values())))
    worst = str(summary.get("worst", "INFO")).upper()
    risk = str(summary.get("risk", summary.get("risk_level", "green")) or "green").lower()
    emoji = {"red": "🔴", "yellow": "🟡", "green": "🟢"}.get(risk, "🟢")

    if total == 0:
        return "\n".join(
            [
                f"# Diff Risk Dashboard {emoji} — No findings",
                "",
                "> ✅ No findings detected (all severities are 0).",
                "",
                "> Generated by diff-risk-dashboard CLI",
            ]
        )

    lines = [
        f"# Diff Risk Dashboard {emoji} — Worst: **{worst}**",
        "",
        "| Severity | Count |",
        "|---|---:|",
    ]
    for sev in _SEVERITIES:
        lines.append(f"| {sev} | {counts.get(sev, 0)} |")
    lines.append(f"| **TOTAL** | **{total}** |")
    lines.append("")
    lines.append("> Generated by diff-risk-dashboard CLI")
    return "\n".join(lines)
