name: Feature request
description: Solicitar mejora
labels: [enhancement]
body:
  - type: textarea
    attributes: { label: Propuesta, placeholder: ¿Qué y por qué? }
    validations: { required: true }
