name: CI / build
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  python:
    name: python (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11","3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install tools
        run: pip install pytest mypy ruff black

      - name: Install project
        run: pip install -e .

      - name: Ruff
        run: ruff check .

      - name: Black (check)
        run: black --check .

      - name: Pytest
        env:
          PYTHONPATH: src
        run: pytest -q

      - name: mypy (solo 3.12)
        if: ${{ matrix.python-version == '3.12' }}
        run: mypy src
