name: CI / build
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  python:
    name: python (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix: { python-version: ["3.11","3.12"] }
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python-version }} }
      - run: python -m pip install -U pip
      - run: pip install pytest mypy ruff black
      - run: ruff check .
      - run: black --check .
      - run: pytest -q
      - name: mypy (solo 3.12)
        if: matrix.python-version == '3.12'
        run: mypy src
