name: dependabot metadata and labels
on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
jobs:
  label:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: noop
        run: echo "labels applied (if any)"
