name: dependabot metadata and labels
on: pull_request_target
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
