name: nightly
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
permissions: { contents: read }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with: { python-version: '3.12' }
      - run: python -m pip install -U pip
      - run: pip install poetry
      - run: poetry install --no-interaction
      - run: poetry run ruff check .
      - run: poetry run black --check .
      - env: { PYTHONPATH: src }
        run: poetry run pytest -q
      - run: poetry run mypy src
