name: publish-pypi
on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  pypi:
    if: startsWith(github.event.release.tag_name, 'v')
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python -m pip install -U pip build
      - name: Sync version from tag into pyproject.toml
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          VER="${TAG#v}"
          export VER
          python - <<'PY'
import os, re, pathlib
ver = os.environ["VER"]
p = pathlib.Path("pyproject.toml")
t = p.read_text(encoding="utf-8")
t = re.sub(r'(?m)^(\s*version\s*=\s*")\d+\.\d+\.\d+(")', rf'\1{ver}\2', t)
p.write_text(t, encoding="utf-8")
print("pyproject.toml version ->", ver)
PY
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
