name: publish-on-semrel

on:
  workflow_run:
    workflows: ["semantic-release"]
    types: [completed]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag a publicar (ej. v0.4.35)"
        required: false
        type: string

jobs:
  publish:
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout (con tags)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Resolver TAG
        id: tag
        shell: bash
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" && -n "${{ github.event.inputs.tag }}" ]]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            git fetch --tags --force
            TAG="$(git tag -l 'v*' --sort=-v:refname | head -n1)"
          fi
          echo "TAG=$TAG" | tee -a "$GITHUB_ENV"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "Publicando TAG=$TAG"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build sdist & wheel
        run: |
          python -m pip install -U pip build
          python -m build

      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.TAG }}
          platforms: linux/amd64
