name: publish-pypi
on:
  workflow_dispatch: {}   # Solo manual (seguro)

permissions:
  contents: read
  id-token: write         # OIDC (sin token)

jobs:
  pypi:
    environment: pypi     # coincide con PyPI (opcional, recomendado)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: python -m pip install -U pip build
      - run: python -m build              # genera dist/*
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/             # OIDC -> no password
