name: publish-pypi
on:
  release:
    types: [published]       # se dispara cuando semantic-release crea el release
  workflow_dispatch:         # también manual si lo necesitas
permissions:
  id-token: write
  contents: read
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: python -m pip install --upgrade pip build
      - run: python -m build
      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
