name: release
on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  ghcr:
    if: startsWith(github.event.release.tag_name, 'v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set env
        run: |
          echo "TAG=${{ github.event.release.tag_name }}" >> "$GITHUB_ENV"
          echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}"   >> "$GITHUB_ENV"
      - name: Build & push (amd64+arm64)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t "$IMAGE:$TAG" -t "$IMAGE:latest" \
            --push .
