name: release
on:
  push:
    tags: ['v*']          # cuando semantic-release crea el tag
  release:
    types: [published]    # cuando el GitHub Release se publica

permissions:
  contents: read
  packages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ghcr:
    runs-on: ubuntu-latest
    env:
      # nombre de imagen SIEMPRE en minúsculas
      IMAGE: ghcr.io/${{ github.repository }}
      TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Lowercase image name
        run: echo "IMAGE=${IMAGE,,}" >> "$GITHUB_ENV"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: ${{ env.IMAGE }}:latest,${{ env.IMAGE }}:${{ env.TAG }}
